---
title: "Identify Siblings"
author: Casey Breen
---

Summary: This notebook contains code to identify brothers in census records by linking the 1920 census to the 1940 census. 

```{r}
## library packages 
library(data.table)
library(tidyverse)
library(here)
```

## Read in data 

```{r}
## read in ABE crosswalk 
xwalk_1920_1940 <- fread("/90days/casey/1920-1940/1920-1940/data/crosswalk_1920_1940.csv")

## read in 1920 census 
census_1920 <- fread("/home/ipums/casey-ipums/IPUMS2019/1920/TSV/P.tsv", select = c("AGE", "SEX", "HISTID", "SERIALP", "RELATE")) %>% 
  janitor::clean_names()

## read in 1940 census linked to 1920 census 
censoc_dmf <- fread("/censoc/data/censoc_linked_with_census/1940_v2.1/censoc_dmf_v2_1_linked_with_census.csv")
```

## Identify Siblings

```{r}
## identify men age 5-16 in the 1940 census 
siblings_1920 <- census_1920 %>% 
  filter(age %in% c(5:16)) %>% 
  filter(sex == 1) %>% 
  rename_all(paste0, "_1920")

## match 1920 and 1940 census 
siblings_matched <- siblings_1920 %>% 
  inner_join(xwalk_1920_1940, by = "histid_1920") %>% 
  filter(link_abe_exact_standard == 1) %>% 
  rename(link_abe_exact_conservative_1920_1940 = link_abe_exact_conservative)

## identify siblings (already restricted to link_abe_exact_standard == 1)
censoc_dmf_linked <- censoc_dmf %>% 
  rename(serialp_1940 = serialp) %>% 
  rename(link_abe_exact_conservative_1940_dmf = link_abe_exact_conservative) %>% 
  inner_join(siblings_matched, by = c("histid" = "histid_1940")) 

## identify linked siblings  
censoc_dmf_linked_sibs_final <- censoc_dmf_linked %>% 
  filter(byear %in% 1905:1915) %>% 
  group_by(serialp_1920) %>% 
  filter(n() > 1) %>% 
  ungroup()
```


```{r}
## write out linked census file
fwrite(censoc_dmf_linked_sibs_final, here("data/censoc_sibs.csv"))
```



