---
title: "Home Ownership Analysis"
author: Casey Breen
---


Summary: code to look at relationship between home ownership and longevity. 

```{r}
## library packages
library(data.table)
library(tidyverse)
library(ipumsr)
library(socviz)
library(broom)
library(cowplot)
library(fixest)
library(here)
```


```{r}
## read in dmf 
dmf <- fread("/censoc/data/censoc_linked_with_census/1940_v2.1/censoc_dmf_v2_1_linked_with_census.csv")


## recode some variables 
dmf <- dmf %>% 
  mutate(bpld = bpl) %>% 
  janitor::clean_names(case = "all_caps")

## read in IPUMS DDI for IPUMS extract
## we already have a ddi on the server for all vars! but can also make a new extract from IPUMS with BPLD var  
ddi_extract <- read_ipums_ddi("/data/josh/CenSoc/censoc_data/ipums_1940_extract/fullcount.ddi.xml")

## rename our bpl var to match the IPUMS var BPLD

## assign metadata using ipumsr package
dmf <- ipums_collect(data = dmf, ddi = ddi_extract, var_attrs = c("val_labels", "var_label", "var_desc"))

## create new string variable bpl_string 
dmf <- dmf %>% 
  mutate(bpl_string = as_factor(BPLD)) %>% 
  janitor::clean_names()

## read in sibling mortality data 
dmf_sibs <- fread(here("data/censoc_sibs.csv")) %>% 
  janitor::clean_names()

```


```{r}
## dmf analysis 
dmf_analysis <- dmf %>% 
  filter(byear %in% 1905:1915) %>% 
  janitor::clean_names() %>% 
  mutate(ownership = relevel(as.factor(ownershp), ref = "20")) %>% 
  filter(ownership != 0) %>% 
  filter(relate == 101) %>% 
  censocdev::recode_education(educ_var = educ)

dmf_analysis <- dmf_analysis %>% 
  filter(link_abe_exact_conservative == 1)
```


```{r}
## comparison of pooled vs. total sibs 
pooled_effect <- tidy(fixest::feols(death_age ~ ownership | byear,  dmf_analysis  %>% filter(race == 100))) %>% 
  mutate(type = "pooled") 

pooled_effect_black <- tidy(fixest::feols(death_age ~ ownership | byear ,  dmf_analysis %>% filter(race == 200))) %>% 
  mutate(type = "pooled black") 

sib_effect <- tidy(fixest::feols(death_age ~ ownership | byear,  dmf_sibs)) %>% 
  mutate(type = "sibs")

pooled_effect %>% 
  bind_rows(sib_effect) %>% 
  bind_rows(pooled_effect_black) %>% 
  ggplot(aes(x = type, y = estimate, 
             ymin = estimate + 1.96*std.error,
             ymax = estimate - 1.96*std.error)) + 
  geom_pointrange() + 
  theme_cowplot() + 
  ylim(0, 1)
```




```{r}
dmf_analysis_sibs <- mortality_data %>% 
  mutate(ownership = relevel(as.factor(ownershp), ref = "2")) %>% 
  filter(ownership != 0) %>% 
  filter(relate == 1) %>% 
  group_by(serialp) %>% 
  filter(n() > 1) %>% 
  censocdev::recode_education(educ_var = educd)

dmf_analysis_sibs <- dmf_analysis_sibs %>% 
  arrange(byear) %>% 
  mutate(birth_order = row_number()) %>% ungroup()
 
model1 <- feols(death_age ~ ownership | byear,  data = dmf_analysis_sibs)
model2 <- feols(death_age ~ ownership + educ_yrs | byear + educ_yrs + urban + occ + race + marst + statefip,  data = dmf_analysis_sibs)
model3 <- feols(death_age ~ ownership + educ_yrs | byear + educ_yrs + urban + occ + race + marst + statefip + serialp + birth_order,  data = dmf_analysis_sibs)


results <- tidy(model1) %>% mutate(model = "Baseline") %>% 
  bind_rows(tidy(model2) %>% mutate(model = "Baseline + Controls")) %>% 
  bind_rows(tidy(model3) %>% mutate(model = "Baseline + Controls + Sibling FE")) %>% 
  filter(term == "ownership1")


home_ownership_regression_plot <- results %>% 
    filter(term == "ownership1") %>% 
  mutate(e65 = estimate,
         lower = estimate - 1.96*std.error,
         upper = estimate + 1.96*std.error) %>% 
  mutate(method = "OLS") %>% 
  ggplot(aes(x = model, y = e65, ymin = lower, ymax = upper)) + 
  geom_line() + 
  geom_pointrange(size = 1.1) + 
  theme_cowplot() + 
  ylim(0, 0.9) + 
  labs(x = "Model",
       y = "Additional Years of Life") + 
  ggsci::scale_color_lancet() + 
  theme(legend.position = "NULL")

# title = "Relationship between Home Ownership and Longevity",
# subtitle = "CenSoc-DMF cohorts of 1905-1915, Men-Only"


ggsave(plot = home_ownership_regression_plot, "figures/home_ownership_models.pdf", width = 9, height = 5)
```


```{r}
model1 <- feols(death_age ~ ownership + valueh | byear,  data = dmf_analysis_sibs %>% filter(valueh %in% c(1:90000)))


tidy(feols(death_age ~  valueh | byear,  data = dmf_analysis_sibs %>% filter(valueh %in% c(1:9000))))


dmf_analysis_sibs %>% 
  filter(valueh %in% c(0:9000)) %>% 
  ggplot() +
  geom_histogram(aes(x = valueh),
                 bins = 10, 
                 color = "black",
                 fill = "grey") + 
  theme_cowplot()

dmf_analysis_sibs_homevalue <- dmf_analysis_sibs %>% 
  filter(valueh %in% c(0:9000)) %>% 
  mutate(value_decile = ntile(valueh, 2)) 

tidy(feols(death_age ~  as.factor(value_decile)   |  educ_yrs + byear,  data = dmf_analysis_sibs_homevalue))

  

feols(death_age ~ ownership | byear,  data = dmf_analysis_sibs %>% filter(byear %in% 1905:1910))

feols(death_age ~ ownership | byear,  data = dmf_analysis_sibs %>% filter(byear %in% 1910:1915))
```

```{r}
dmf_analysis_sibs_disaggregate <- dmf_analysis_sibs %>% 
  filter(race %in% 1:2)

feols(death_age ~ as.factor(race) | byear + ownership,  data = dmf_analysis_sibs_disaggregate)


```



```{r}
dmf_analysis_sibs_disaggregate %>% 
  group_by(serialp) %>% 
  summarize(distinct = n_distinct(ownershp)) %>% 
  count(distinct)


subsample <- dmf_analysis_sibs_disaggregate %>% 
  group_by(serialp) %>% 
  filter(n_distinct(ownershp) > 1) 

subsample

feols(death_age ~ ownership | byear + serialp,  data = subsample %>% filter(race == 2))

feols(death_age ~ ownership | byear + educ_yrs + urban + occ + race + marst + statefip + serialp + birth_order,  data = dmf_analysis_sibs)

```

