---
title: "Create Lexis diagram"
---

Summary: Create Lexis diagram demonstrating sample timeline


```{r}
library(LexisPlotR)
library(tidyverse)
```


```{r}
lexis_grid <- function (year_start, year_end, age_start, age_end, delta = 1, 
    lwd = 0.3, force_equal = TRUE) 
{
    if (!is.numeric(year_start)) {
        stop("The value of year_start must be numeric.")
    }
    if (!is.numeric(year_end)) {
        stop("The value of year_end must be numeric.")
    }
    if (!is.numeric(age_start)) {
        stop("The value of age_start must be numeric.")
    }
    if (!is.numeric(age_end)) {
        stop("The value of age_end must be numeric.")
    }
    if (year_start >= year_end) {
        stop("The provided year_start is not earlier than the provided year_end.")
    }
    if (age_start >= age_end) {
        stop("The provided age_start is not smaller than the provided age_end.")
    }
    year_start <- as.Date(paste(year_start, "-01-01", sep = ""))
    year_end <- as.Date(paste(year_end, "-01-01", sep = ""))
    year_seq <- seq(year_start, year_end, by = "year")
    age_seq <- age_start:age_end
    year_zero <- as.Date("1970-01-01")
    diff_zero <- as.numeric(round((year_start - year_zero)/365.25))
    diff_year <- as.numeric(round((year_end - year_start)/365.25))
    diff_dia <- diff_year - 1
    m <- merge(year_seq, age_seq)
    lexis <- ggplot() + theme_bw()
    lexis <- lexis + geom_blank(data = m, aes(x = .data$x, y = .data$y))
    lexis <- lexis + geom_abline(intercept = seq(-diff_dia - 
        100, diff_dia + 100, delta) - 1, slope = 1/365.25, lwd = lwd, color = "grey")
    lexis <- lexis + scale_x_date(breaks = year_seq[seq(1, length(year_seq), 
        delta)], expand = c(0, 0), date_labels = "%Y")
    lexis <- lexis + scale_y_continuous(expand = c(0, 0), breaks = age_seq[seq(1, 
        length(age_seq), delta)])
    lexis <- lexis + theme(panel.grid.major = element_line(colour = "grey", 
        size = lwd))
    lexis <- lexis + theme(panel.grid.minor = element_blank())
    lexis <- lexis + labs(x = "", y = "")
    if (force_equal == TRUE) {
        lexis <- lexis + coord_fixed(ratio = 365.25, xlim = c(year_start, 
            year_end), ylim = c(age_start, age_end))
    }
    return(lexis)
}
```





```{r}
lexis <- lexis_grid(year_start = 1900, year_end = 2010, age_start = 0, age_end = 110, delta = 10)

lexis <- lexis_cohort(lg = lexis, cohort = c(1905))
lexis <- lexis_cohort(lg = lexis, cohort = c(1906))
lexis <- lexis_cohort(lg = lexis, cohort = c(1907))
lexis <- lexis_cohort(lg = lexis, cohort = c(1908))
lexis <- lexis_cohort(lg = lexis, cohort = c(1909))
lexis <- lexis_cohort(lg = lexis, cohort = c(1910))
lexis <- lexis_cohort(lg = lexis, cohort = c(1911))
lexis <- lexis_cohort(lg = lexis, cohort = c(1912))
lexis <- lexis_cohort(lg = lexis, cohort = c(1913))
lexis <- lexis_cohort(lg = lexis, cohort = c(1914))
lexis <- lexis_cohort(lg = lexis, cohort = c(1915)) 

p <- lexis

p <- p + 
  labs(x = "Year", y = "Age", "title" = "Analytical Sample") + 
  theme(axis.text.x = element_text(angle = 90))

p <- p + geom_vline(xintercept =  as.Date(paste(1920, "-01-01", sep = "")), color = "Blue", linetype = "dashed", size = .7) + 
    annotate("text", x = as.Date(paste(1908, "-01-01", sep = "")), 
                y = 20, label = "1920 Census \n (Identify Sibs)", size= 2.4, 
                colour='blue')+ 
   annotate("segment", 
           x = as.Date(paste(1914, "-01-01", sep = "")), xend = as.Date(paste(1919, "-01-01", sep = "")), y = 20, yend = 20,
           arrow=arrow(length=unit(0.2, "cm")), color = "blue", size = .7)

ggsave(plot = p, "figures/lexis_diagram_1.png", width = 7, height = 5)


p <- p + geom_vline(xintercept =  as.Date(paste(1940, "-01-01", sep = "")), color = "Blue", linetype = "dashed", size = .7) + 
   annotate("text", x = as.Date(paste(1928, "-01-01", sep = "")), 
                y = 40, label = "1940 Census \n (Covariates)", size= 2.4, 
                colour='blue') +
   annotate("segment", 
           x = as.Date(paste(1934, "-01-01", sep = "")), xend = as.Date(paste(1939, "-01-01", sep = "")), y = 40, yend = 40,
           arrow=arrow(length=unit(0.2, "cm")), color = "blue", size = .7)

ggsave(plot = p, "figures/lexis_diagram_2.png", width = 7, height = 5)


p <- p + annotate("rect", xmin = as.Date(paste(2005, "-01-01", sep = "")), xmax = as.Date(paste(1975, "-01-01", sep = "")), ymin = 60, ymax = 110, alpha = .2, fill = "red") + 
   annotate("text", x = as.Date(paste(1957, "-01-01", sep = "")), 
                y = 80, label = "Mortality Observation Window \n (1975-2005)", size= 2.4, 
                colour='red') +
   annotate("segment", 
           x = as.Date(paste(1970, "-01-01", sep = "")), xend = as.Date(paste(1975, "-01-01", sep = "")), y = 80, yend = 80,
           arrow=arrow(length=unit(0.2, "cm")), color = "red", size = .7)

  
positions <- data.frame(x = c(as.Date(paste(1975, "-01-01", sep = "")), as.Date(paste(1975, "-01-01", sep = "")), as.Date(paste(2005, "-01-01", sep = "")), as.Date(paste(2005, "-01-01", sep = ""))),
                        y = c(59, 70, 100, 90 ))

p <- p + geom_polygon(aes(x = positions$x, y = positions$y), fill = "NA", color = "black", linetype = "dashed", size= .7)

ggsave(plot = p, "figures/lexis_diagram_3.png", width = 7, height = 5)
```

```{r}
library(LexisPlotR)
library(ggplot2)
library(HMDHFDplus)

triangles <- HMDHFDplus::readHMDweb(CNTRY = "RUS", "Deaths_lexis", Sys.getenv("HMD_USER"), Sys.getenv("HMD_PASSWORD"))

tidy_triangles <- tidy_triangle_data(triangles)

lg <- lexis_grid(1960, 2000, 30, 80, delta = 5)

lg + geom_polygon(data = tidy_triangles, aes(x = x, y = y, group = id, fill = Total))
```
