---
title: "Home Ownership and Mortality by Quintile"
author: Casey Breen
---

## Library packages 

```{r}
## library packages
library(data.table)
library(tidyverse)
library(ipumsr)
library(socviz)
library(broom)
library(cowplot)
library(fixest)
library(here)
source(here("code/helpers.R"))
```

## calculate homeownership value quartile

```{r}
## find values of households 
hh <- fread("/ipums-repo2019/1940/TSV/H.tsv")

## restrict to hoes with non-missing values for ownership 
hh_homes <- hh %>% 
  filter(OWNERSHP == 10)
 
## filter to only homes with a non-missing values 
hh_homes <- hh_homes %>% 
  filter(VALUEH != 9999998)

## split into quartiles 
hh_homes <- hh_homes %>% 
  group_by(STATEFIP) %>% 
  mutate(hvalue_state = ntile(VALUEH, 4)) %>% 
  ungroup()
```

## Link analysis file onto CenSoc file 

```{r}
## Read in sibling file 
dmf_sibs <- fread(here("code/analysis_file/censoc_analysis_sibs.csv")) %>% 
  janitor::clean_names()

## dmf sibs 
dmf_sibs <- dmf_sibs %>% 
  left_join(hh_homes %>% select(serialp_1940 = SERIAL, hvalue_state))

## recode dmf sibs 
dmf_analysis_sibs_new <- dmf_sibs %>% 
  filter(ownership != 10 | valueh != 9999998) %>% 
  mutate(ownership_value = case_when(
    ownership == 10 & hvalue_state == 1 ~ 1,
    ownership == 10 & hvalue_state == 2 ~ 2,
    ownership == 10 & hvalue_state == 3 ~ 3,
    ownership == 10 & hvalue_state == 4 ~ 4,
    TRUE ~ 0
    ))

## run models 
model1 <- tidy(feols(death_age ~ as.factor(ownership_value)  | byear,  data = dmf_analysis_sibs_new)) %>% mutate(model = "No Controls")
model2 <- tidy(feols(death_age ~ as.factor(ownership_value)  | byear + educ_yrs + urban + occ + race + marst + statefip,  data = dmf_analysis_sibs_new)) %>% mutate(model = "Controls")
model3 <- tidy(feols(death_age ~ as.factor(ownership_value)  | byear + educ_yrs + urban + occ + race + marst + statefip + serialp_1920,  data = dmf_analysis_sibs_new)) %>% mutate(model = "Controls + Sibling FE")

## effect heterogeneity 
home_ownership_homevalue_plot_1models <- model3 %>% 
  # bind_rows(model2) %>% 
  # bind_rows(model1) %>% 
  mutate(term = case_when(
    term == "as.factor(ownership_value)1" ~ "Q1 (Low)",
    term == "as.factor(ownership_value)2" ~ "Q2",
    term == "as.factor(ownership_value)3" ~ "Q3",
    term == "as.factor(ownership_value)4" ~ "Q4 (High)"
  )) %>% 
  mutate(e65 = estimate,
         lower = estimate - 1.96*std.error,
         upper = estimate + 1.96*std.error) %>% 
  ggplot(aes(x = term, y = e65, ymin = lower, ymax = upper, group = model, color = model, shape = model)) + 
    geom_line(alpha = 0.6, linetype = "dashed") + 
  geom_pointrange(size = 0.7,  fill = "white", shape = 21, position = position_dodge2(.1)) + 
  theme_cowplot() + 
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey") + 
  labs(x = "Home Value Quartile",
       y = "Additional Years of Life") + 
  #  ggsci::scale_color_lancet() + 
  scale_color_manual(values = c("Controls + Sibling FE" = "#008B45FF")) + 
  # scale_color_viridis_d(option = "m") + 
  theme(legend.position = "bottom") + 
  annotate("text", x = 3.5, y = -.05, label = "Renters",
           parse = TRUE)

## effect heterogeneity 
home_ownership_homevalue_plot_3models <- model1 %>% 
  bind_rows(model2) %>% 
  bind_rows(model3) %>% 
  mutate(term = case_when(
    term == "as.factor(ownership_value)1" ~ "Q1 (Low)",
    term == "as.factor(ownership_value)2" ~ "Q2",
    term == "as.factor(ownership_value)3" ~ "Q3",
    term == "as.factor(ownership_value)4" ~ "Q4 (High)"
  )) %>% 
  mutate(model = factor(model, levels= c("No Controls", "Controls", "Controls + Sibling FE"))) %>% 
  mutate(e65 = estimate,
         lower = estimate - 1.96*std.error,
         upper = estimate + 1.96*std.error) %>% 
  ggplot(aes(x = term, y = e65, ymin = lower, ymax = upper, group = model, color = model, shape = model)) + 
    geom_line(alpha = 0.6, linetype = "dashed") + 
  geom_pointrange(size = 0.7,  fill = "white", shape = 21, position = position_dodge2(.1)) + 
  theme_cowplot() + 
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey") + 
  scale_color_manual(values = cud) + 
  labs(x = "Home Value Quartile",
       y = "Additional Years of Life") + 
  # scale_color_viridis_d(option = "m") + 
  theme(legend.position = "bottom") + 
  annotate("text", x = 3.5, y = -.05, label = "Renters",
           parse = TRUE)

## homeownership plot 1 
ggsave(plot = home_ownership_homevalue_plot_1models, "figures/home_ownership_homevalue_plot_1models.png", width = 6, height = 4)

## homeownership plot 3 
ggsave(plot = home_ownership_homevalue_plot_3models, "figures/home_ownership_homevalue_plot_3models.png", width = 6, height = 4)
```


## Alternative 

```{r}
# dmf_analysis_sibs_new <- dmf_analysis_sibs %>% 
#   filter(ownership != 10 | valueh != 9999998) %>% 
#   mutate(ownership_value = case_when(
#     ownership == 10 & valueh %in% c(1:700) ~ 1,
#     ownership == 10 & valueh %in% c(700:2000) ~ 2,
#     ownership == 10 & valueh %in% c(2000:3500) ~ 3,
#     ownership == 10 & valueh %in% c(3500:10000) ~ 4,
#     TRUE ~ 0
#     ))
# 
# ## run models 
# model1 <- tidy(feols(death_age ~ as.factor(ownership_value)  | byear,  data = dmf_analysis_sibs_new)) %>% mutate(model = "No Controls")
# model2 <- tidy(feols(death_age ~ as.factor(ownership_value)  | byear + educ_yrs + urban + occ + race + marst + statefip,  data = dmf_analysis_sibs_new)) %>% mutate(model = "Controls")
# model3 <- tidy(feols(death_age ~ as.factor(ownership_value)  | byear + educ_yrs + urban + occ + race + marst + statefip + serialp_1920,  data = dmf_analysis_sibs_new)) %>% mutate(model = "Controls + Sibling FE")
# 
# ## effect heterogeneity 
# home_ownership_homevalue_plot_1models <- model3 %>% 
#   # bind_rows(model2) %>% 
#   # bind_rows(model1) %>% 
#   mutate(term = case_when(
#     term == "as.factor(ownership_value)1" ~ "Q1 (Low)",
#     term == "as.factor(ownership_value)2" ~ "Q2",
#     term == "as.factor(ownership_value)3" ~ "Q3",
#     term == "as.factor(ownership_value)4" ~ "Q4 (High)"
#   )) %>% 
#   mutate(e65 = estimate,
#          lower = estimate - 1.96*std.error,
#          upper = estimate + 1.96*std.error) %>% 
#   ggplot(aes(x = term, y = e65, ymin = lower, ymax = upper, group = model, color = model, shape = model)) + 
#     geom_pointrange(size = 0.7,  fill = "white", shape = 21, position = position_dodge2(.1)) + 
#   geom_line(alpha = 0.6, linetype = "dashed") + 
#   theme_cowplot() + 
#   geom_hline(yintercept = 0, linetype = "dashed", color = "grey") + 
#   labs(x = "Home Value Quartile",
#        y = "Additional Years of Life") + 
#  #  ggsci::scale_color_lancet() + 
#   scale_color_manual(values = c("Controls + Sibling FE" = "#009E73")) + 
#   # scale_color_viridis_d(option = "m") + 
#   theme(legend.position = "bottom") + 
#     annotate("text", x = 3.5, y = -.05, label = "Renters",
#   parse = TRUE)
# 
# ggsave(plot = home_ownership_homevalue_plot_1models, "figures/home_ownership_homevalue_plot_1models.png", width = 6, height = 4)
# 
# ## effect heterogeneity 
# home_ownership_homevalue_plot_3models <- model1 %>% 
#   bind_rows(model2) %>% 
#   bind_rows(model3) %>% 
#   mutate(term = case_when(
#     term == "as.factor(ownership_value)1" ~ "Q1 (Low)",
#     term == "as.factor(ownership_value)2" ~ "Q2",
#     term == "as.factor(ownership_value)3" ~ "Q3",
#     term == "as.factor(ownership_value)4" ~ "Q4 (High)"
#   )) %>% 
#   mutate(model = factor(model, levels= c("No Controls", "Controls", "Controls + Sibling FE"))) %>% 
#   mutate(e65 = estimate,
#          lower = estimate - 1.96*std.error,
#          upper = estimate + 1.96*std.error) %>% 
#   ggplot(aes(x = term, y = e65, ymin = lower, ymax = upper, group = model, color = model, shape = model)) + 
#     geom_pointrange(size = 0.7,  fill = "white", shape = 21, position = position_dodge2(.1)) + 
#   geom_line(alpha = 0.6, linetype = "dashed") + 
#   theme_cowplot() + 
#   geom_hline(yintercept = 0, linetype = "dashed", color = "grey") + 
#     scale_color_manual(values = cud) + 
#   # ggsci::scale_color_aaas() + 
#   labs(x = "Home Value Quartile",
#        y = "Additional Years of Life") + 
#   # scale_color_viridis_d(option = "m") + 
#   theme(legend.position = "bottom") + 
#     annotate("text", x = 3.5, y = -.05, label = "Renters",
#   parse = TRUE)
# 
# ggsave(plot = home_ownership_homevalue_plot_3models, "figures/home_ownership_homevalue_plot_3models.png", width = 6, height = 4)
```

